// SPDX-FileCopyrightText: Copyright (C) 2026 National University of Singapore
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

#pragma once

#include "../receiver/ofh_ru_cplane_scheduling_dispatcher.h"
#include "ofh_ru_uplink_request_repository.h"
#include "ocudu/ocudulog/logger.h"
#include "ocudu/ran/subcarrier_spacing.h"
#include <memory>

namespace ocudu {
namespace ofh {

/// O-RU uplink scheduling recorder configuration.
struct ru_uplink_scheduling_recorder_config {
  /// Radio sector identifier.
  unsigned sector;
  /// PUSCH/cell subcarrier spacing.
  subcarrier_spacing scs;
  /// RU operating bandwidth in PRBs.
  unsigned ru_nof_prbs;
};

/// \brief Records received uplink and PRACH Control-Plane scheduling requests into context repositories.
///
/// This is the store-and-respond-later uplink model a real O-RU needs: instead of replying to an uplink/PRACH
/// Control-Plane request immediately (as the test-IQ emulator does), it records the request, keyed by slot and
/// eAxC, in the uplink/PRACH request repositories. A later symbol-driven responder builds the User-Plane
/// reply once the corresponding uplink IQ has been captured (by a real radio, or generated by a fake one).
///
/// It is the O-RU mirror of how the O-DU records the uplink Control-Plane it scheduled.
class ru_uplink_scheduling_recorder : public ru_uplink_scheduling_handler
{
public:
  ru_uplink_scheduling_recorder(const ru_uplink_scheduling_recorder_config&   config,
                                ocudulog::basic_logger&                       logger_,
                                std::shared_ptr<ru_uplink_request_repository> ul_request_repo_,
                                std::shared_ptr<ru_uplink_request_repository> prach_request_repo_);

  // See interface for documentation.
  void handle_uplink_scheduling(unsigned eaxc, const cplane_message_decoder_results& results) override;

  // See interface for documentation.
  void handle_prach_scheduling(unsigned eaxc, const cplane_message_decoder_results& results) override;

private:
  ocudulog::basic_logger&                       logger;
  std::shared_ptr<ru_uplink_request_repository> ul_request_repo;
  std::shared_ptr<ru_uplink_request_repository> prach_request_repo;
  const unsigned                                sector_id;
  const subcarrier_spacing                      scs;
  const unsigned                                ru_nof_prbs;
};

} // namespace ofh
} // namespace ocudu
